name: Go Backend Build Check

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Install dependencies
      run: |
        cd backend
        go mod download

    - name: Build
      run: |
        cd backend
        go build -v ./cmd/server

    - name: Verify build completed
      run: |
        echo "✅ Build successful!"
